<?php

/*********************************************************************
 * Extension configuration file for ext "context_hints".
 *
 * Generated by ext 11-08-2014 15:44 UTC
 *
 * https://github.com/t3elmar/Ext
 *********************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Display hints about the current Application Context',
	'description' => 'Displays a little message on the top of the Backend about the current context along with some useful info as tooltip.
                    After configuring and installing the extension, reload the Backend and notice the additional info next to the TYPO3 logo.',
	'category' => 'be',
	'author' => 'Fabien Udriot',
	'author_email' => 'fabien.udriot@typo3.org',
	'state' => 'stable',
	'clearCacheOnLoad' => 0,
	'version' => '1.2.0-dev',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
