<?php

/*********************************************************************
* Extension configuration file for ext "vidi".
*
* Generated by ext 09-04-2014 14:53 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Display a little hint in the Backend about the current Application Context',
  'description' => 'Displays a little message on the top of the Backend about the current context along with some useful info as tooltip.
                    After configuring and installing the extension, reload the Backend and notice the additional info next to the TYPO3 logo.',
  'category' => 'be',
  'author' => 'Fabien Udriot',
  'author_email' => 'fabien.udriot@typo3.org',
  'state' => 'stable',
  'clearCacheOnLoad' => 0,
  'version' => '1.0.0',
  array (
    'depends' =>
    array (
      'cms' => '',
      'fluid' => '',
      'typo3' => '6.2.0-6.2.99',
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
      'metadata' => '',
    ),
  ),
  'user' => 'fab1en',
  'comment' => '',
);

?>